config/routes.rb
Rails.application.routes.draw do
  resources :keywords
  resources :post_types
  resources :commentars
  resources :commetars
  resources :posts
  devise_for :users
  resources :posts do
    resources :commentars, only: [:create]
  end





  root 'home#index'
  get '/search', to: 'home#search', as: 'search'
  get '/search_type', to: 'home#search_posts_type', as: 'search_posts_type'
  get '/search_by_author', to: 'home#search_posts_author', as: 'search_posts_author'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/controllers/post_types_controller.rb
class PostTypesController < ApplicationController
  before_action :set_post_type, only: %i[ show edit update destroy ]

  # GET /post_types or /post_types.json
  def index
    @post_types = PostType.all
  end

  # GET /post_types/1 or /post_types/1.json
  def show
  end

  # GET /post_types/new
  def new
    @post_type = PostType.new
  end

  # GET /post_types/1/edit
  def edit
  end

  # POST /post_types or /post_types.json
  def create
    @post_type = PostType.new(post_type_params)

    respond_to do |format|
      if @post_type.save
        format.html { redirect_to post_type_url(@post_type), notice: "Post type was successfully created." }
        format.json { render :show, status: :created, location: @post_type }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_types/1 or /post_types/1.json
  def update
    respond_to do |format|
      if @post_type.update(post_type_params)
        format.html { redirect_to post_type_url(@post_type), notice: "Post type was successfully updated." }
        format.json { render :show, status: :ok, location: @post_type }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_types/1 or /post_types/1.json
  def destroy
    # Удалить связанные записи в таблице "posts"
    # @post_type.posts.destroy_all

    # Удалить запись в таблице "post_types"
    @post_type.destroy

    respond_to do |format|
      format.html { redirect_to post_types_url, notice: "Post type was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_type
      @post_type = PostType.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_type_params
      params.require(:post_type).permit(:type)
    end
end

app/helpers/post_types_helper.rb
module PostTypesHelper
end

app/views/post_types/_form.html.erb
<%= form_with(model: post_type) do |form| %>
  <% if post_type.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(post_type.errors.count, "error") %> prohibited this post_type from being saved:</h2>

      <ul>
        <% post_type.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Тип_поста, class: "form-label" %>
    <%= form.text_field :type, class: "form-control col-md-3" %>
  </div>

  <div>
    <%= form.submit "Виконати", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/post_types/_post_type.html.erb
<div id="<%= dom_id post_type %>">
  <p>
    <strong>Type:</strong>
    <%= post_type.type %>
  </p>

</div>

app/views/post_types/edit.html.erb
<h1>Редагування</h1>

<%= render "form", post_type: @post_type %>

<br>

<div>
  <%= link_to "Повернутися", post_types_path %>
</div>

app/views/post_types/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Типи постів</h1>

<div id="News">
  <table class="table table table-striped table table-bordered table table-hover">
    <thead class="thead-dark">
    <tr>
      <th>Тип</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @post_types.each do |postType| %>
      <tr>
        <td><%= postType.type %></td>
        <td>
          <%#= link_to "Редагувати", edit_post_path(post), class:"btn btn-secondary" %>
          <%= link_to "Редагувати", post_type_path(postType), class: "btn btn-danger", method: :delete, data: { confirm: "Вы уверены?" } %>
          <%#= link_to "Show", patient %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<!--<div id="posts">-->
<%# @posts.each do |post| %>
<%#= render post %>
<!--    <p>-->
<%#= link_to "Детальніше", post %>
<!--    </p>-->
<%# end %>
<!--</div>-->

<%= link_to "Створити новий пост", new_post_type_path %>

app/views/post_types/new.html.erb
<h1>Додати новий тип поста</h1>

<%= render "form", post_type: @post_type %>

<br>

<div>
  <%= link_to "Повернутися", post_types_path %>
</div>

app/views/post_types/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="card">
  <div class="card-body">
    <h5 class="card-title">Тип поста: <%= @post_type.type %></h5>

  </div>
</div>

<div>

  <% if @post_type.posts.empty? %>
    <%= button_to "Видалити", @post_type, method: :delete, class: "btn btn-danger pb-2 mb-4 mt-3" %>
  <% else %>
    <br>
    <p>Неможливо видалити тип поста, так як він має пов'язані пости.</p>
  <% end %>

  <br>
  <%= link_to "Редагувати", edit_post_type_path(@post_type), class: "btn btn-primary"%>
  <%= link_to "Повернутися", post_types_path, class: "btn btn-primary" %>


</div>