config/routes.rb
Rails.application.routes.draw do
  resources :keywords
  resources :post_types
  resources :commentars
  resources :commetars
  resources :posts
  devise_for :users
  resources :posts do
    resources :commentars, only: [:create]
  end





  root 'home#index'
  get '/search', to: 'home#search', as: 'search'
  get '/search_type', to: 'home#search_posts_type', as: 'search_posts_type'
  get '/search_by_author', to: 'home#search_posts_author', as: 'search_posts_author'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @posts = Post.all
  end

  # def search
  #   search_query = params[:search]
  #
  #   keywords = Keyword.where("keyword LIKE ?", "%#{search_query}%")
  #   posts = Post.joins(:keywords).where(keywords: { id: keywords })
  #
  #   @search_results = posts
  #
  #   render 'home/search'
  # end
  def search
    search_query = params[:search]

    if search_query.present?
      keywords = search_query.split(" ").map(&:downcase)
      conditions = keywords.map { |keyword| "keywords.keyword LIKE ?" }
      search_conditions = conditions.join(" OR ")
      search_arguments = keywords.map { |keyword| "%#{keyword}%" }

      @search_results = Post.joins(:keywords).where(search_conditions, *search_arguments)
    else
      @search_results = []
    end

    render 'home/search'
  end

  # def search_posts_type
  #   post_type_id = params[:post_type]
  #   puts "post_type_id: #{post_type_id}"
  #
  #
  #   if post_type_id.present?
  #     @search_results = Post.joins(:post_type).where(post_types: { id: post_type_id })
  #   else
  #     @search_results = []
  #   end
  #
  #   puts "@search_results: #{@search_results.inspect}"
  #
  #   render 'home/search_type'
  # end



  def search_posts_type
    post_type_id = params[:post_type]
    # puts "post_type_id: #{post_type_id}"

    post_type = PostType.find(post_type_id)
    @search_results = post_type.posts
    # if post_type_id.present?
    #   @search_results = Post.joins().where(post_type_id: post_type_id)
    # else
    #   @search_results = []
    # end

    puts "@search_results: #{@search_results.inspect}"

    render 'home/search_type'
  end

  def search_posts_author
    author_id = params[:search_posts_author]
    # puts "post_type_id: #{post_type_id}"

    author = Author.find(author_id)
    @search_results = author.posts
    # if post_type_id.present?
    #   @search_results = Post.joins().where(post_type_id: post_type_id)
    # else
    #   @search_results = []
    # end

    puts "@search_results: #{@search_results.inspect}"

    render 'home/search_type'
  end





end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <%= link_to 'News Website', root_path, class:"navbar-brand" %>
  <% if user_signed_in? %>
    <% user = User.find_by(id: current_user.id) %>
    <h3 class="text-white"><%= user.name %></h3>

<% end %>
  <!--  <a class="navbar-brand" href="#"></a>-->
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>

        <li class="nav-item active">

          <%= link_to "Вийти", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
        <li class="nav-item active">
          <%= link_to "Налаштування", edit_user_registration_path, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item active">
          <%= link_to "Увійти", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
      <% if current_user %>
        <% if Author.exists?(user_id: current_user.id) %>
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Таблиці
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown" data-turbolinks-eval="false">

              <%= link_to "Posts", posts_path, class: "dropdown-item" %>
              <%= link_to "Post Types", post_types_path, class: "dropdown-item" %>
              <%= link_to "Keywords", keywords_path, class: "dropdown-item" %>
              <%#= link_to "Departments", departments_path, class: "dropdown-item" %>
              <%#= link_to "Patients Cards", patient_cards_path, class: "dropdown-item" %>
              <%#= link_to "Specializations", specializations_path, class: "dropdown-item" %>


          <!--          <a class="dropdown-item" href="#">Action1</a>-->
          <!--          <a class="dropdown-item" href="#">Another action</a>-->
          <!--          <div class="dropdown-divider"></div>-->
          <!--          <a class="dropdown-item" href="#">Something else here</a>-->

        </div>
      </li>
        <% end %>
      <% end %>
        <!--      <li class="nav-item">-->
        <!--        <a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>-->
        <!--      </li>-->
    </ul>

    <form class="form-inline my-2 my-lg-0" action="<%= search_posts_author_path %>" method="GET">
      <div class="input-group">
        <%= select_tag 'search_posts_author', options_for_select(Author.all.map { |auth| [auth.user.name, auth.id] }), prompt: 'Оберіть Автора', class: 'custom-select' %>
        <div class="input-group-append">
          <button class="btn btn-outline-success my-2 my-sm-0 ml-2 mr-4" type="submit">Search</button>
        </div>
      </div>
    </form>

    <form class="form-inline my-2 my-lg-0" action="<%= search_posts_type_path %>" method="GET">
      <div class="input-group">
        <%= select_tag 'post_type', options_for_select(PostType.all.map { |pt| [pt.type, pt.id] }), prompt: 'Оберіть тип поста', class: 'custom-select' %>
        <div class="input-group-append">
          <button class="btn btn-outline-success my-2 my-sm-0 ml-2 mr-4" type="submit">Search</button>
        </div>
      </div>
    </form>



    <form class="form-inline my-2 my-lg-0" action="<%= search_path %>" method="get">
      <input class="form-control mr-sm-2" type="search" placeholder="Ключове слово" aria-label="Search" name="search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Пошук</button>
    </form>


  </div>
</nav>

app/views/home/index.html.erb
<h1>Новини</h1>
<div id="News">
  <div class="list-group">
    <% @posts.each do |post| %>
      <div class="list-group-item">
        <h3 class="mb-1"><%= post.title %></h3>
        <br>
        <p class="mb-1"><%= post.post_text %></p>
        <h6 class="mb-1">Тип: <%= post.post_type.type %></h6>

        <h6 class="mb-1">Автор: <%= post.authors.first&.user&.name %></h6>
        <h6> Ключові слова:
          <% post.keywords.each do |keyword| %>
            <%= keyword.keyword %>,
          <% end %>
        </h6>



        <small><%= post.created_at %></small>

<!--        <h6>Коментарі:</h6>-->
        <%# post.commentars.each do |commentar| %>
<!--          <div class="card mb-3">-->
<!--            <div class="card-header">-->
              <%#= commentar.user.name %>
<!--            </div>-->
<!--            <div class="card-body">-->
<!--              <p class="card-text"><%#= commentar.commentar_text %></p>-->
<!--            </div>-->
<!--            <div class="card-footer text-muted">-->
              <%#= commentar.created_at %>
<!--            </div>-->
<!--          </div>-->
        <%# end %>

        <div class="mt-2">
          <% if current_user %>
            <% if Author.exists?(user_id: current_user.id) %>
              <% author = Author.find_by(user_id: current_user.id) %>
              <%= link_to "Редагувати", edit_post_path(post), class: "btn btn-secondary mr-2" %>
              <%= link_to "Докладніше", post_path(post), class: "btn btn-secondary mr-2" %>
            <% else %>
              <%#= form_with(model: [post, Commentar.new]) do |form| %>
                <%#= form.hidden_field :post_id, value: post.id %>
                <%#= form.text_area :commentar_text, class: "form-control", placeholder: "Введіть ваш коментар" %>
                <%#= form.submit "Додати комментар", class: "btn btn-primary mt-2" %>
              <%# end %>
              <%= link_to "Докладніше", post_path(post), class: "btn btn-secondary mr-2" %>
            <% end %>
          <% else %>
            <p>Будьласка, увійдіть в систему для виконання дій.</p>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/home/search.html.erb
<ul>
  <h1>Результати пошуку</h1>
<% if @search_results.any? %>


    <% @search_results.each do |post| %>
      <div class="list-group-item">
        <h3 class="mb-1 "><%= post.title %></h3>
        <br>
        <p class="mb-1"><%= post.post_text %></p>
        <h6 class="mb-1">Тип: <%= post.post_type.type %></h6>

        <h6 class="mb-1">Автор: <%= post.authors.first&.user&.name %></h6>
        <h6> Ключові слова:
          <% post.keywords.each do |keyword| %>
            <%= keyword.keyword %>,
          <% end %>
        </h6>



        <small><%= post.created_at %></small>

        <!--        <h6>Коментарі:</h6>-->
        <%# post.commentars.each do |commentar| %>
        <!--          <div class="card mb-3">-->
        <!--            <div class="card-header">-->
        <%#= commentar.user.name %>
        <!--            </div>-->
        <!--            <div class="card-body">-->
        <!--              <p class="card-text"><%#= commentar.commentar_text %></p>-->
        <!--            </div>-->
        <!--            <div class="card-footer text-muted">-->
        <%#= commentar.created_at %>
        <!--            </div>-->
        <!--          </div>-->
        <%# end %>

        <div class="mt-2">
          <% if current_user %>
            <% if Author.exists?(user_id: current_user.id) %>
              <% author = Author.find_by(user_id: current_user.id) %>
              <%= link_to "Редагувати", edit_post_path(post), class: "btn btn-secondary mr-2" %>
              <%= link_to "Докладніше", post_path(post), class: "btn btn-secondary mr-2" %>
            <% else %>
              <%#= form_with(model: [post, Commentar.new]) do |form| %>
              <%#= form.hidden_field :post_id, value: post.id %>
              <%#= form.text_area :commentar_text, class: "form-control", placeholder: "Введіть ваш коментар" %>
              <%#= form.submit "Додати комментар", class: "btn btn-primary mt-2" %>
              <%# end %>
              <%= link_to "Докладніше", post_path(post), class: "btn btn-secondary mr-2" %>
            <% end %>
          <% else %>
            <p>Пожалуйста, войдите в систему для выполнения действий.</p>
          <% end %>
        </div>
      </div>
    <% end %>

<% else %>
  <p>Немає результатів</p>
<% end %>
</ul>

app/views/home/search_by_author.html.erb
<ul>
  <h1>Результати пошуку</h1>

<% if @search_results.any? %>


    <% @search_results.each do |post| %>
      <div class="list-group-item">
        <h3 class="mb-1"><%= post.title %></h3>
        <br>
        <p class="mb-1"><%= post.post_text %></p>
        <h6 class="mb-1">Тип: <%= post.post_type.type %></h6>

        <h6 class="mb-1">Автор: <%= post.authors.first&.user&.name %></h6>
        <h6> Ключові слова:
          <% post.keywords.each do |keyword| %>
            <%= keyword.keyword %>,
          <% end %>
        </h6>



        <small><%= post.created_at %></small>

        <!--        <h6>Коментарі:</h6>-->
        <%# post.commentars.each do |commentar| %>
        <!--          <div class="card mb-3">-->
        <!--            <div class="card-header">-->
        <%#= commentar.user.name %>
        <!--            </div>-->
        <!--            <div class="card-body">-->
        <!--              <p class="card-text"><%#= commentar.commentar_text %></p>-->
        <!--            </div>-->
        <!--            <div class="card-footer text-muted">-->
        <%#= commentar.created_at %>
        <!--            </div>-->
        <!--          </div>-->
        <%# end %>

        <div class="mt-2">
          <% if current_user %>
            <% if Author.exists?(user_id: current_user.id) %>
              <% author = Author.find_by(user_id: current_user.id) %>
              <%= link_to "Редагувати", edit_post_path(post), class: "btn btn-secondary mr-2" %>
              <%= link_to "Докладніше", post_path(post), class: "btn btn-secondary mr-2" %>
            <% else %>
              <%#= form_with(model: [post, Commentar.new]) do |form| %>
              <%#= form.hidden_field :post_id, value: post.id %>
              <%#= form.text_area :commentar_text, class: "form-control", placeholder: "Введіть ваш коментар" %>
              <%#= form.submit "Додати комментар", class: "btn btn-primary mt-2" %>
              <%# end %>
              <%= link_to "Докладніше", post_path(post), class: "btn btn-secondary mr-2" %>
            <% end %>
          <% else %>
            <p>Пожалуйста, войдите в систему для выполнения действий.</p>
          <% end %>
        </div>
      </div>
    <% end %>

<% else %>
  <p>Немає результатів</p>
<% end %>
</ul>

app/views/home/search_type.html.erb
<ul>
  <h1>Результати пошуку</h1>

<% if @search_results.any? %>
    <% @search_results.each do |post| %>
      <div class="list-group-item">
        <h3 class="mb-1"><%= post.title %></h3>
        <br>
        <p class="mb-1"><%= post.post_text %></p>
        <h6 class="mb-1">Тип: <%= post.post_type.type %></h6>

        <h6 class="mb-1">Автор: <%= post.authors.first&.user&.name %></h6>
        <h6> Ключові слова:
          <% post.keywords.each do |keyword| %>
            <%= keyword.keyword %>,
          <% end %>
        </h6>



        <small><%= post.created_at %></small>

        <!--        <h6>Коментарі:</h6>-->
        <%# post.commentars.each do |commentar| %>
        <!--          <div class="card mb-3">-->
        <!--            <div class="card-header">-->
        <%#= commentar.user.name %>
        <!--            </div>-->
        <!--            <div class="card-body">-->
        <!--              <p class="card-text"><%#= commentar.commentar_text %></p>-->
        <!--            </div>-->
        <!--            <div class="card-footer text-muted">-->
        <%#= commentar.created_at %>
        <!--            </div>-->
        <!--          </div>-->
        <%# end %>

        <div class="mt-2">
          <% if current_user %>
            <% if Author.exists?(user_id: current_user.id) %>
              <% author = Author.find_by(user_id: current_user.id) %>
              <%= link_to "Редагувати", edit_post_path(post), class: "btn btn-secondary mr-2" %>
              <%= link_to "Докладніше", post_path(post), class: "btn btn-secondary mr-2" %>
            <% else %>
              <%#= form_with(model: [post, Commentar.new]) do |form| %>
              <%#= form.hidden_field :post_id, value: post.id %>
              <%#= form.text_area :commentar_text, class: "form-control", placeholder: "Введіть ваш коментар" %>
              <%#= form.submit "Додати комментар", class: "btn btn-primary mt-2" %>
              <%# end %>
              <%= link_to "Докладніше", post_path(post), class: "btn btn-secondary mr-2" %>
            <% end %>
          <% else %>
            <p>Пожалуйста, войдите в систему для выполнения действий.</p>
          <% end %>
        </div>
      </div>
    <% end %>

<% else %>
  <p>Немає результатів</p>
<% end %>
</ul>