config/routes.rb
Rails.application.routes.draw do
  resources :keywords
  resources :post_types
  resources :commentars
  resources :commetars
  resources :posts
  devise_for :users
  resources :posts do
    resources :commentars, only: [:create]
  end





  root 'home#index'
  get '/search', to: 'home#search', as: 'search'
  get '/search_type', to: 'home#search_posts_type', as: 'search_posts_type'
  get '/search_by_author', to: 'home#search_posts_author', as: 'search_posts_author'
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  devise_scope :user do
    get '/users/sign_out', to: 'devise/sessions#destroy'
  end
end

app/models/keyword.rb
class Keyword < ApplicationRecord
  has_and_belongs_to_many :posts, join_table: :keyword_and_posts
end

app/controllers/keywords_controller.rb
class KeywordsController < ApplicationController
  before_action :set_keyword, only: %i[ show edit update destroy ]

  # GET /keywords or /keywords.json
  def index
    @keywords = Keyword.all
  end

  # GET /keywords/1 or /keywords/1.json
  def show
  end

  # GET /keywords/new
  def new
    @keyword = Keyword.new
  end

  # GET /keywords/1/edit
  def edit
  end

  # POST /keywords or /keywords.json
  def create
    @keyword = Keyword.new(keyword_params)

    respond_to do |format|
      if @keyword.save
        format.html { redirect_to keyword_url(@keyword), notice: "Keyword was successfully created." }
        format.json { render :show, status: :created, location: @keyword }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /keywords/1 or /keywords/1.json
  def update
    respond_to do |format|
      if @keyword.update(keyword_params)
        format.html { redirect_to keyword_url(@keyword), notice: "Keyword was successfully updated." }
        format.json { render :show, status: :ok, location: @keyword }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @keyword.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /keywords/1 or /keywords/1.json
  def destroy
    @keyword.destroy

    respond_to do |format|
      format.html { redirect_to keywords_url, notice: "Keyword was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_keyword
      @keyword = Keyword.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def keyword_params
      params.require(:keyword).permit(:keyword)
    end
end

app/helpers/keywords_helper.rb
module KeywordsHelper
end

app/views/keywords/_form.html.erb
<%= form_with(model: keyword) do |form| %>
  <% if keyword.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(keyword.errors.count, "error") %> prohibited this keyword from being saved:</h2>

      <ul>
        <% keyword.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :Ключове_слово, class: "form-label" %>
    <%= form.text_field :keyword, class: "form-control col-md-3" %>
  </div>
  <br>
  <div>
    <%= form.submit "Виконати", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/keywords/_keyword.html.erb
<div id="<%= dom_id keyword %>">
  <p>
    <strong>Keyword:</strong>
    <%= keyword.keyword %>
  </p>

</div>

app/views/keywords/edit.html.erb
<h1>Редагувати ключове слово</h1>

<%= render "form", keyword: @keyword %>

<br>

<div>
  <%= link_to "Повернутися", keywords_path %>
</div>

app/views/keywords/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Ключові слова</h1>

<div id="News">
  <table class="table table table-striped table table-bordered table table-hover">
    <thead class="thead-dark">
    <tr>
      <th>Ключове слово</th>
      <th colspan="3"></th>
    </tr>
    </thead>
    <tbody>
    <% @keywords.each do |keyword| %>
      <tr>
        <td><%= keyword.keyword %></td>
        <td>
          <%#= link_to "Редагувати", edit_post_path(post), class:"btn btn-secondary" %>
          <%= link_to "Редагувати", keyword_path(keyword), class: "btn btn-danger", method: :delete, data: { confirm: "Вы уверены?" } %>
          <%#= link_to "Show", patient %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</div>

<!--<div id="posts">-->
<%# @posts.each do |post| %>
<%#= render post %>
<!--    <p>-->
<%#= link_to "Детальніше", post %>
<!--    </p>-->
<%# end %>
<!--</div>-->

<%= link_to "Додати нове ключове слово", new_keyword_path %>

app/views/keywords/new.html.erb
<h1>Нове ключове слово</h1>

<%= render "form", keyword: @keyword %>

<br>

<div>
  <%= link_to "Повернутися", keywords_path %>
</div>

app/views/keywords/show.html.erb
<p style="color: green"><%= notice %></p>


<div class="card">
  <div class="card-body">
    <h5 class="card-title">Тип поста: <%= @keyword.keyword %></h5>

  </div>
</div>

<div>
  <br>
  <%= button_to "Видалити", @keyword, method: :delete, class: "btn btn-danger pb-2 mb-4 mt-3"  %>
  <br>
  <%= link_to "Редагувати", edit_keyword_path(@keyword), class: "btn btn-primary"%>
  <%= link_to "Повернутися", keywords_path, class: "btn btn-primary" %>


</div>